### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by qingjixian** [gmpassos/docker_commander#4]
[SEVERE]	Error processing request: Instance of '_HttpRequest' > operation: stdout ; parameters: {instanceID: 1167, realOffset: 2} ; body:
2023-05-09T14:51:30.791677440Z RangeError (start): Invalid value: Not in inclusive range 0..1: 2
2023-05-09T14:51:30.791679945Z #0      RangeError.checkValidRange (dart:core/errors.dart:333)
2023-05-09T14:51:30.791682407Z #1      _GrowableList.sublist (dart:core-patch/growable_array.dart:84)
2023-05-09T14:51:30.791684762Z #2      OutputStream.getEntries (package:docker_commander/src/docker_commander_host.dart:895)

**Comment by gmpassos** [comment]
Please, check the last version
